In [1]:
import pandas as pd
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
Y = boston.target




C:\Users\z3020\anaconda3\envs\ML\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this case special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California hous

In [2]:
print(X.shape)
print(Y.shape)

(506, 13)
(506,)


In [3]:
from sklearn.model_selection import train_test_split
X = boston.data
Y = boston.target
X_train , X_test , Y_train ,Y_test = train_test_split(X,Y,test_size=0.25,random_state=1000)

In [4]:
import numpy as np
data = ['male' , 'female' , 'female' , 'male']
np.array([ [1,0] if d=='male' else [0,1] for d in data])
np.array( [1 if d=='male' else 0 for d in data])

array([1, 0, 0, 1])

In [7]:
data = ['yes' , 'no' ,'no' ,'yes','maybe']
[1 if d=='yes' else 0 if d=='no' else 2 for d in data]


[1, 0, 0, 1, 2]

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(data)
##無法決定yes no maybe 的數值

array([2, 1, 1, 2, 0], dtype=int64)

In [9]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit_transform(data)


array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [10]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
data = [{'height': 1 , 'length': 0 ,'width': 1},
        {'height': 2 , 'length': 1 ,'width': 0}]
dv.fit_transform(data)

array([[1., 0., 1.],
       [2., 1., 0.]])