In [1]:
import pandas as pd
from sklearn.datasets import load_boston
boston = load_boston()

C:\Users\z3020\anaconda3\envs\tensorflow-gpu\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this case special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Cal

In [2]:
boston.data[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [3]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
scaled_data = ss.fit_transform(boston.data)
scaled_data[0]

array([-0.41978194,  0.28482986, -1.2879095 , -0.27259857, -0.14421743,
        0.41367189, -0.12001342,  0.1402136 , -0.98284286, -0.66660821,
       -1.45900038,  0.44105193, -1.0755623 ])

In [4]:
from sklearn.preprocessing import RobustScaler
rb1 = RobustScaler(quantile_range=(25,75))
scaled_data = rb1.fit_transform(boston.data)
scaled_data

array([[-0.06959315,  1.44      , -0.57164988, ..., -1.33928571,
         0.26190191, -0.63768116],
       [-0.06375455,  0.        , -0.20294345, ..., -0.44642857,
         0.26190191, -0.22188906],
       [-0.06376011,  0.        , -0.20294345, ..., -0.44642857,
         0.06667466, -0.73263368],
       ...,
       [-0.05445006,  0.        ,  0.17350891, ...,  0.69642857,
         0.26190191, -0.57171414],
       [-0.04086745,  0.        ,  0.17350891, ...,  0.69642857,
         0.09641444, -0.48775612],
       [-0.05816351,  0.        ,  0.17350891, ...,  0.69642857,
         0.26190191, -0.34782609]])

In [5]:
# from sklearn.preprocessing import Normalizer
# D = [[4,1,2,2],[1,3,9,3],[5,7,5,1]]
# no = Normalizer(norm='max')
# scaled_data = no.fit_transform(D)
# scaled_data[0]

In [6]:
# scaled_data[1]

In [7]:
# scaled_data[2]

In [8]:
# D = [[4,1,2,2],[1,3,9,3],[5,7,5,1]]
# no = Normalizer(norm='l2')
# scaled_data = no.fit_transform(D)
# scaled_data[0]

In [9]:
from sklearn.preprocessing import Normalizer
no = Normalizer(norm='l2')
scaled_data = no.fit_transform(boston.data)
scaled_data[0]

array([1.26388341e-05, 3.59966795e-02, 4.61957387e-03, 0.00000000e+00,
       1.07590075e-03, 1.31487871e-02, 1.30387972e-01, 8.17924550e-03,
       1.99981553e-03, 5.91945396e-01, 3.05971776e-02, 7.93726783e-01,
       9.95908132e-03])

In [10]:
scaled_data.var(axis=0)

array([1.35912445e-04, 2.19042585e-03, 1.13936480e-04, 2.31938388e-07,
       3.57523064e-08, 7.17145965e-06, 2.34167722e-03, 2.10075635e-05,
       1.15220973e-04, 2.29559216e-02, 3.54219041e-05, 4.42122216e-02,
       1.27562719e-04])

In [11]:
from sklearn.feature_selection import VarianceThreshold
vt = VarianceThreshold(threshold=1e-06)
X_t = vt.fit_transform(scaled_data)
X_t.var(axis=0)


array([1.35912445e-04, 2.19042585e-03, 1.13936480e-04, 7.17145965e-06,
       2.34167722e-03, 2.10075635e-05, 1.15220973e-04, 2.29559216e-02,
       3.54219041e-05, 4.42122216e-02, 1.27562719e-04])

In [12]:
import pandas as pd
df = pd.DataFrame(scaled_data)
df.corr()

0         1         2         3         4         5         6   \
0   1.000000 -0.205192  0.245464 -0.063482 -0.082490 -0.493091  0.086833   
1  -0.205192  1.000000 -0.521011 -0.018833 -0.295368  0.386083 -0.480704   
2   0.245464 -0.521011  1.000000  0.081560  0.413239 -0.449057  0.446556   
3  -0.063482 -0.018833  0.081560  1.000000  0.147321  0.103504  0.115177   
4  -0.082490 -0.295368  0.413239  0.147321  1.000000  0.248086  0.599989   
5  -0.493091  0.386083 -0.449057  0.103504  0.248086  1.000000 -0.038815   
6   0.086833 -0.480704  0.446556  0.115177  0.599989 -0.038815  1.000000   
7  -0.418761  0.643931 -0.627556 -0.051694 -0.258357  0.579272 -0.493383   
8   0.614061 -0.313237  0.281220 -0.039560 -0.212984 -0.699097  0.025017   
9   0.549387 -0.328365  0.456853 -0.075415 -0.120496 -0.796949  0.079468   
10 -0.376433  0.032697 -0.197157 -0.016335  0.205663  0.587491  0.048141   
11 -0.590330  0.297844 -0.447110  0.070136  0.041660  0.679878 -0.129902   
12  0.251341 -0.374457  0.479574 -0.002416  0.365536 -0.381343  0.496527   

          7         8         9         10        11        12  
0  -0.418761  0.614061  0.549387 -0.376433 -0.590330  0.251341  
1   0.643931 -0.313237 -0.328365  0.032697  0.297844 -0.374457  
2  -0.627556  0.281220  0.456853 -0.197157 -0.447110  0.479574  
3  -0.051694 -0.039560 -0.075415 -0.016335  0.070136 -0.002416  
4  -0.258357 -0.212984 -0.120496  0.205663  0.041660  0.365536  
5   0.579272 -0.699097 -0.796949  0.587491  0.679878 -0.381343  
6  -0.493383  0.025017  0.079468  0.048141 -0.129902  0.496527  
7   1.000000 -0.561763 -0.617397  0.489528  0.578780 -0.325799  
8  -0.561763  1.000000  0.802666 -0.580860 -0.812470  0.167301  
9  -0.617397  0.802666  1.000000 -0.653434 -0.940041  0.256100  
10  0.489528 -0.580860 -0.653434  1.000000  0.536451  0.043358  
11  0.578780 -0.812470 -0.940041  0.536451  1.000000 -0.296458  
12 -0.325799  0.167301  0.256100  0.043358 -0.296458  1.000000