In [1]:
import numpy as np
X = np.random.randint(2, size=(300, 12))
Y = np.random.randint(2, size=300)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)


In [2]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X_train, Y_train)
bnb.score(X_test, Y_test)   

0.4266666666666667

In [3]:
bnb.predict(X_train[3:4])

array([0])

In [4]:
data = [ {'house': 100, 'street': 50, 'shop': 25, 'car': 100, 'tree': 20},
{'house': 5, 'street': 5, 'shop': 0, 'car': 10, 'tree': 500, 'river': 1} ]


In [5]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
X = dv.fit_transform(data)
Y = np.array([1, 0])

In [6]:
X

array([[100., 100.,   0.,  25.,  50.,  20.],
       [ 10.,   5.,   1.,   0.,   5., 500.]])

In [7]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB(alpha=1.0)
mnb.fit(X, Y)


MultinomialNB()

In [8]:
test_data = [
{'house': 80, 'street': 20, 'shop': 15, 'car': 70, 'tree': 10, 'river': 1},
{'house': 10, 'street': 5, 'shop': 1, 'car': 8, 'tree': 300, 'river': 0} ]
mnb.predict(dv.fit_transform(test_data))

array([1, 0])

In [9]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
nb_samples = 300
X, Y = make_classification(n_samples=nb_samples, n_features=2, n_informative=2, n_redundant=0)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)


In [10]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)
gnb.score(X_test, Y_test)


0.8266666666666667

In [11]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, Y_train)
lr.score(X_test, Y_test)


0.8133333333333334

In [12]:
Y_gnb_score = gnb.predict_proba(X_test)
Y_lr_score = lr.predict_proba(X_test)
from sklearn.metrics import roc_curve, auc
fpr_gnb, tpr_gnb, thresholds_gnb = roc_curve(Y_test, Y_gnb_score[:, 1])
fpr_lr, tpr_lr, thresholds_lr = roc_curve(Y_test, Y_lr_score[:,1])
auc(fpr_gnb, tpr_gnb)


0.9149560117302054

In [13]:
auc(fpr_lr, tpr_lr)


0.9149560117302054

In [14]:
Y_lr_score = lr.decision_function(X_test)
fpr_lr, tpr_lr, thresholds_lr = roc_curve(Y_test, Y_lr_score)
auc(fpr_lr, tpr_lr)


0.9149560117302054