In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
import pandas as pd
X = pd.DataFrame(data=iris.data)
X.shape

(150, 4)

In [3]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

In [5]:
import numpy as np
import numpy.linalg as linalg
cov_mat = np.cov(X_std.T)
cov_mat.shape

(4, 4)

In [7]:
eig_vals , eig_vecs = linalg.eig(cov_mat)
eig_vals

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [8]:
eig_vecs

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])

In [9]:
eig_vecs[:,0]

array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])

In [11]:
eig_pairs = [(np.abs(eig_vals[i]),eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs.sort()
eig_pairs.reverse()
eig_pairs

[(2.938085050199996,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])),
 (0.9201649041624885,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (0.147741821044948,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.020853862176462127,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]

In [14]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(4,1),eig_pairs[1][1].reshape(4,1)))
Y = X_std.dot(matrix_w)
matrix_w 


array([[ 0.52106591, -0.37741762],
       [-0.26934744, -0.92329566],
       [ 0.5804131 , -0.02449161],
       [ 0.56485654, -0.06694199]])

In [15]:
Y.shape

(150, 2)

In [16]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
Y_sklearn = pca.fit_transform(X_std)
Y[0:5]

array([[-2.26470281, -0.4800266 ],
       [-2.08096115,  0.67413356],
       [-2.36422905,  0.34190802],
       [-2.29938422,  0.59739451],
       [-2.38984217, -0.64683538]])

In [17]:
Y_sklearn[0:5]

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538]])

In [18]:
pca.explained_variance_ratio_

array([0.72962445, 0.22850762])